### ISSUE TITLE
PR for official todomvc repo?

### ISSUE THREAD

**Issue by user-one** [evancz/elm-todomvc#13]
Elm isn't displayed on http://todomvc.com

Is there anything lacking the implementation for it to be accepted?

If not, I would also suggest that _maybe_ http://elm-lang.org/blog/Blazing-Fast-Html.elm is included in the sidebar of links since this is what converted me to elm

**Comment by jmfayard** [comment]
:+1: for being accepted on http://todomvc.com
I have found it very useful and convincing

**Comment by evancz** [comment]
There's [a PR open](https://github.com/tastejs/todomvc/pull/1041) to do this thanks to @passy, but it got stalled on me not having enough time to really focus on everything going on right now. I'm currently struggling to balance some work at Prezi with the 0.15 release, so if anyone in this thread is able, it'd be a huge help to get this working!

**Comment by passy** [comment]
I'm in the same boat trying to find a proper balance between OSS, events and work. I'm still super keen on getting this into TodoMVC. The test flakiness described in the issue is probably okay, because it's more likely an issue with the test runner than with Elm, but someone would have to look into the learn bar and positioning the app correctly.

If someone would be interested in helping out, that would be fantastic!

**Comment by evancz** [comment]
I posted on [the mailing list](https://groups.google.com/forum/#!topic/elm-discuss/_77roZZAoBc), but maybe it'd be good to ask for help on twitter? I'll try it out once it's daytime in SF and Budapest.
