### ISSUE TITLE
error initializing TODO module with null state

### ISSUE THREAD

**Issue by neocris** [evancz/elm-todomvc#44]
the first time i run these app `savedModel` is null because `localStorage` is empty yet so the init function gets an error because it is expecting a `Model` instead. this is rather strange since the type argument of init signature is `Maybe Model`

**Comment by evancz** [comment]
I am unable to reproduce this. The `init` function takes a `Maybe Model` which should handle `null` values. What OS and browser and version of Elm are you using? Can you say more about what you did to get this error? Perhaps you compiled with `elm-make Todo.elm` instead of using the [build instructions](https://github.com/evancz/elm-todomvc#build-instructions).

**Comment by neocris** [comment]
it works now. the module i had was named Todo but i have it installed in a folder with a diff name, then i renamed the folder with the same name as the module to get it right. but i have to retract an imprecision i made before since the error was about `Elm.Todo` being undefined, not null, and was not related to `init` either. my mistake was due to another bug in my code involving `init` that at the time of filling this issue got short-circuited with the one i was actually making. thanks for your trouble.
